### ISSUE TITLE
Ghost Placing on blocks when click on cake

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [OmnifactoryDevs/DimensionalEdibles#12]
When you click on a cake with an item in your hand, or with an item in your offhand like a torch, the game will show the item being placed before teleporting you via the cake. However, when you return to the cake, there will not be a block placed.

We should figure out a way to prevent this block being placed from being shown.

**Comment by Exaxxion** [comment]
I wonder if the code is running on both the server and the client, but not accounting for it properly on the client. This could create a desync where the client thinks the appropriate response is placing a block but the server teleports the player.
