### ISSUE TITLE
[Gradle] Could not find ForgeGradle.jar

### ISSUE THREAD

**Issue by Custom2044** [OmnifactoryDevs/DimensionalEdibles#26]
I tried following the readme as a test project and got this error :

`./gradlew setupDecompWorkspace

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'DimensionalEdibles'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find ForgeGradle.jar (com.github.GregTechCE:ForgeGradle:FG_2.3-SNAPSHOT).
     Searched in the following locations:
         https://jitpack.io/com/github/GregTechCE/ForgeGradle/FG_2.3-SNAPSHOT/ForgeGradle-FG_2.3-v2.0.2-gf36092e-250.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s`

**Comment by Exaxxion** [comment]
Jitpack has been having some weird issues recently and that's what has been causing the builds to fail like that. It's specifically failing to resolve the ForgeGradle artifacts from jitpack.io which is necessary to do pretty much anything else related to the build.

**Comment by Custom2044** [comment]
Ok, thanks for the fast answer

**Comment by Exaxxion** [comment]
I just rebuilt my checkout from scratch (no existing local artifacts) on the first try so it seems to work at least intermittently.

**Comment by Custom2044** [comment]
Still the same error, I'll try again later.
What surprises me is that putting the URL into my browser starts the download just fine.

**Comment by Custom2044** [comment]
Ok it finally worked, thank you.
