### ISSUE TITLE
Spawing below bedrock in overworld

### ISSUE THREAD

**Issue by htmlcsjs** [OmnifactoryDevs/DimensionalEdibles#6]
I spawn below bedrock in the overworld, though my overworld got corrupted when i moved OS

see: https://discord.com/channels/564247906991996928/564247906991996930/804652230099599400

**Comment by Exaxxion** [comment]
We can't reasonably account for world corruption (you should restore from a backup if that happens), but this may already be fixed as of 3d0c282 ([beta 1.4.3](https://www.curseforge.com/minecraft/mc-mods/dimensional-edibles-omnifactory-edition/files/3185463)).

The same logic used for finding a valid spawn platform in the nether also applies to the overworld.

**Comment by htmlcsjs** [comment]
ill try the beta later, but the world was corrupted ages ago and i think the backup went with it, as it was full disk corruption

**Comment by smudgerox** [comment]
I don't think world corruption has anything to do with this issue, my world was perfectly fine except for spawning below bedrock.

**Comment by Exaxxion** [comment]
I'm just saying in general if you have world corruption you can't really expect anything to work right.

In this case the same bug is happening in your overworld as most players are experiencing in the nether. No valid position for the player to spawn between Y=0 and the build limit for the targeted X,Z was found, so it spawns you at Y=0 resulting in falling out of the world.

We believe this issue is fixed by the aforementioned beta release.

**Comment by htmlcsjs** [comment]
the overwold reset, just to let you know

**Comment by Exaxxion** [comment]
@htmlcsjs One thing we missed asking when reviewing this before was whether you have the `B:useWorldSpawn` option set to `true` or `false` in the `overworldcake` section of your config. This would affect whether it will always try to place you directly above the Overworld's spawn point, or whether it calculates a spawn location like other cakes.

We have also published [Beta 1.4.6](https://www.curseforge.com/minecraft/mc-mods/dimensional-edibles-omnifactory-edition/files/3198748) so you can try using the `/dimensionalEdibles invalidate <Player> <dimID>` command on yourself to see if that helps. Use `-1` for Nether, `0` for Overworld, and `1` for The End for the `dimID` argument.

**Comment by htmlcsjs** [comment]
My config had `B:useWorldSpawn` disabled, so ill try enabling that. Do i need to update the client and server or just the server for Beta 1.4.6?

**Comment by Exaxxion** [comment]
It's more for context as to which algorithm is being used. When `B:useWorldSpawn` is `false` then the Overworld Cake uses the same placement algorithm as the Nether Cake.

You need the same jar on both the Client and Server.

**Comment by Exaxxion** [comment]
This issue should be resolved as of [1.12.2-1.5 (GitHub)](https://github.com/OmnifactoryDevs/DimensionalEdibles/releases/tag/1.12.2-1.5) (or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/dimensional-edibles-omnifactory-edition/files/3270146)).

Be sure to invalidate any bad spawn positions cached on players using: ```/de invalidate <PlayerName> <dimID>```
